before:
    hooks:
        - go mod tidy
        
builds:
    -   id: "gobana-agent"
        binary: "gobana-agent"
        env:
            - CGO_ENABLED=0
            - GO111MODULE=on
        goos:
            - linux
            - darwin
        goarch:
            - amd64
            - arm64
        flags:
            - -trimpath
            
checksum:
    algorithm: sha512
    
nfpms:
    - id: agent
      package_name: gobana-agent
      
      vendor: thomasglachant
      homepage: https://github.com/thomasglachant/gobana-agent
      maintainer: Thomas Glachant <thomas@glth.fr>
      
      formats:
          - deb
      
      bindir: /usr/bin
      contents:
          - src: ./resources/dist/init/gobana-agent.service
            dst: /lib/systemd/system/gobana-agent.service
          - src: ./resources/dist/config/gobana_agent.yaml
            dst: /etc/gobana/agent.yaml
            type: config
      
      scripts:
          postinstall: ./resources/dist/scripts/postinstall.sh
          preremove: ./resources/dist/scripts/preremove.sh
          postremove: ./resources/dist/scripts/postremove.sh

snapshot:
    name_template: "{{ incpatch .Version }}-next"

release:
    github:
        owner: thomasglachant
        name: gobana-agent
    prerelease: auto

changelog:
    sort: asc
    filters:
        exclude:
            - '^docs:'
            - '^test:'
            - '^docs:'
            - '^test:'
            - '^dev:'
            - 'README'
            - 'build\(deps\): bump .* in /docs \(#\d+\)'
            - Merge pull request
            - Merge branch
