before:
    hooks:
        - go mod tidy
builds:
    -   id: "spooter-agent"
        binary: "spooter-agent"
        dir: agent
        env:
            - CGO_ENABLED=0
            - GO111MODULE=on
        goos:
            - linux
            - darwin
        goarch:
            - amd64
            - arm64
        flags:
            - -trimpath
        ldflags:
            - -s -w    
    -   id: "spooter-server"
        binary: "spooter-server"
        dir: server
        env:
            - CGO_ENABLED=0
            - GO111MODULE=on
        goos:
            - linux
            - darwin
        goarch:
            - amd64
            - arm64
        flags:
            - -trimpath
        ldflags:
            - -s -w
archives:
    -   replacements:
            linux: Linux
            386: i386
            amd64: x86_64
            
checksum:
    algorithm: sha512
    

nfpms:
    - id: agent
      package_name: spooter-agent
      
      vendor: thomasglachant
      homepage: https://github.com/thomasglachant/spooter
      maintainer: Thomas Glachant <thomas@glth.fr>
      
      formats:
          - deb
      
      bindir: /usr/bin
      contents:
          - src: ../dist/init/spooter_agent.service
            dst: /lib/systemd/system/spooter_agent.service
          - src: ../dist/config/spooter_agent.yaml
            dst: /etc/spooter/agent.yaml
            type: config
      
      scripts:
          postinstall: ../dist/scripts/postinstall_agent.sh
          preremove: ../dist/scripts/preremove_agent.sh
          postremove: ../dist/scripts/postremove_agent.sh
          
    - id: server
      package_name: spooter-server
      
      vendor: thomasglachant
      homepage: https://github.com/thomasglachant/spooter
      maintainer: Thomas Glachant <thomas@glth.fr>
      
      formats:
          - deb
      
      bindir: /usr/bin
      contents:
          - src: ../dist/init/spooter_server.service
            dst: /lib/systemd/system/spooter_server.service
          - src: ../dist/config/spooter_server.yaml
            dst: /etc/spooter/server.yaml
            type: config
      
      scripts:
          postinstall: ../dist/scripts/postinstall_server.sh
          preremove: ../dist/scripts/preremove_server.sh
          postremove: ../dist/scripts/postremove_server.sh

snapshot:
    name_template: "{{ incpatch .Version }}-next"

changelog:
    sort: asc
    filters:
        exclude:
            - '^docs:'
            - '^test:'
            - '^docs:'
            - '^test:'
            - '^dev:'
            - 'README'
            - 'build\(deps\): bump .* in /docs \(#\d+\)'
            - Merge pull request
            - Merge branch
