---
name: CI
on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.19'

      - name: Check go mod
        run: |
            go mod tidy
            git diff --exit-code go.mod

      - name: Build
        run: make build

      - name: Test fmt
        run: make fmt

      - name: Test linter
        run: make lint

      - name: Tests unit
        run: make test
