---
name: CI
on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18'

      - name: Check go mod
        run: |
          for i in agent server core; do
            go mod tidy
            git diff --exit-code go.mod
          done

      - name: Build agent
        run: make build-agent
      - name: Build server
        run: make build-server

      - name: Test Fmt
        run: make fmt

      - name: TestLinter
        run: make lint

      - name: Tests
        run: make test
