name: Release

concurrency: 'release_environment'

on:
    push:
        tags:
            - '*'

jobs:
    test:
        name: Tests
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: Set up Go
                uses: actions/setup-go@v2
                with:
                    go-version: '^1.19'

            -   name: Check go mod
                run: |
                    go mod tidy
                    git diff --exit-code go.mod

            -   name: Build
                run: make build

            -   name: Test fmt
                run: |
                    make fmt
                    git diff --exit-code

            -   name: Test linter
                run: make lint

            -   name: Tests unit
                run: make test-unit


    release:
        name: Build and create release
        runs-on: ubuntu-latest
        needs: [ test ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: Set up Go
                uses: actions/setup-go@v2
                with:
                    go-version: '^1.19'

            -   name: Create release
                uses: goreleaser/goreleaser-action@v2
                with:
                    version: latest
                    args: release --rm-dist
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
